services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "127.0.0.1", "--eval", "db.runCommand('ping').ok"] #
      interval: 10s
      retries: 5
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "rootuser"
      ME_CONFIG_BASICAUTH_PASSWORD: "securepassword"
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: securepassword
      ME_CONFIG_MONGODB_URL: mongodb://rootuser:securepassword@mongo:27017/
    # This 'depends_on' ensures mongo starts before mongo-express
    depends_on:
      - mongo

volumes:
  mongo-data:
